name: Test
on: [push]

jobs:
  Look-into-xrdp-CI-fail:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install all_i386
        run: |
          sudo scripts/install_xrdp_build_dependencies_with_apt.sh max i386 --allow-downgrades --allow-remove-essential --allow-change-held-packages
